"""Reusable relationship analysis helpers."""

from core.relationships.geometry import (
    ASSOCIATION_CLASS_TAXONOMY,
    BLOCK_ORDER,
    DISCRETE_BINS,
    DISCRETE_LABELS,
    FDR_ORDINAL_BINS,
    FDR_ORDINAL_LABELS,
    FDR_SIGNALS,
    GEOMETRY_TAXONOMY,
    HAUL_DROP_MATERIAL,
    HAUL_THRESHOLD_PTS,
    MATCH_LEVEL_SIGNALS,
    MIN_ACTIVE_BINS,
    MIN_N_HAUL,
    MIN_N_PANEL_PLAYERS,
    MIN_N_PER_BIN,
    MIN_N_SHAPE,
    MONOTONIC_GEOMETRIES,
    MONO_CONF_HIGH,
    MONO_CONF_LOW,
    PANEL_CLASS_THRESHOLDS,
    POPULATION_ROBUSTNESS_VALUES,
    POPULATION_SCOPE_VALUES,
    POSITIONS,
    QUANTILE_N_BINS,
    SPARSE_THRESHOLD,
    SUPPORT_TYPE_TAXONOMY,
    TWO_STAGE_NZ_LABELS,
    UPPER_TAIL_GEOMETRIES,
    bin_analysis,
    classify_geometry,
    get_bin_direction,
    monotonicity_confidence,
    select_bucketing_scheme,
    stability_classify,
)
from core.relationships.association import (
    assign_association_class,
    consolidate_flags,
)
from core.relationships.panel import decompose_rho
from core.relationships.tail import haul_concentration

__all__ = [
    "assign_association_class",
    "ASSOCIATION_CLASS_TAXONOMY",
    "BLOCK_ORDER",
    "DISCRETE_BINS",
    "DISCRETE_LABELS",
    "FDR_ORDINAL_BINS",
    "FDR_ORDINAL_LABELS",
    "FDR_SIGNALS",
    "GEOMETRY_TAXONOMY",
    "HAUL_DROP_MATERIAL",
    "HAUL_THRESHOLD_PTS",
    "MATCH_LEVEL_SIGNALS",
    "MIN_ACTIVE_BINS",
    "MIN_N_HAUL",
    "MIN_N_PANEL_PLAYERS",
    "MIN_N_PER_BIN",
    "MIN_N_SHAPE",
    "MONOTONIC_GEOMETRIES",
    "MONO_CONF_HIGH",
    "MONO_CONF_LOW",
    "PANEL_CLASS_THRESHOLDS",
    "POPULATION_ROBUSTNESS_VALUES",
    "POPULATION_SCOPE_VALUES",
    "POSITIONS",
    "QUANTILE_N_BINS",
    "SPARSE_THRESHOLD",
    "SUPPORT_TYPE_TAXONOMY",
    "TWO_STAGE_NZ_LABELS",
    "UPPER_TAIL_GEOMETRIES",
    "bin_analysis",
    "classify_geometry",
    "consolidate_flags",
    "decompose_rho",
    "get_bin_direction",
    "haul_concentration",
    "monotonicity_confidence",
    "select_bucketing_scheme",
    "stability_classify",
]
