"""ADR-010 ruling (c) — composition recommendation/decision separation.

synth01_decisions.yaml is now generated by merging the study's recommendation
(synth01_recommendations.yaml) with governance's ratification (synth01_annotations.yaml).
This guards:
  1. the generator reproduces the committed decision-of-record (drift guard + the
     reproduce-before-retire gate),
  2. governance ratification is the authority — an override in annotations flows into
     the decision, separating recommendation from decision,
  3. fail-closed merge — an unratified recommendation (or orphan ratification) raises.
"""

from __future__ import annotations

import copy
from pathlib import Path

import pytest
import yaml

from model.governance.generate_synth01_decisions import (
    ANNOTATIONS_PATH,
    RECOMMENDATIONS_PATH,
    generate,
)

pytestmark = pytest.mark.unit

DECISIONS_PATH = Path("model/assemble/synth01_decisions.yaml")


def _norm(data: dict) -> dict:
    out = copy.deepcopy(data)
    out["decisions"] = {d["key"]: d for d in out["decisions"]}
    return out


def _committed() -> dict:
    with DECISIONS_PATH.open() as fh:
        return yaml.safe_load(fh)


def test_generated_matches_committed() -> None:
    """Generator output equals the committed composition decision-of-record."""
    assert _norm(generate()) == _norm(_committed())


def test_ratification_is_the_authority(tmp_path: Path) -> None:
    """A governance override in annotations flows into the decision (not the recommendation)."""
    rec = yaml.safe_load(RECOMMENDATIONS_PATH.read_text())
    ann = yaml.safe_load(ANNOTATIONS_PATH.read_text())

    # Pick an APPROVED recommendation and have governance override it to EXCLUDED-REDUNDANT.
    target = next(a for a in ann["annotations"] if a["ratified_decision"].startswith("APPROVED"))
    target["ratified_decision"] = "EXCLUDED-REDUNDANT"
    target["ratified_weight"] = 0.0
    target["ratified_contribution_class"] = "redundant"
    target["rationale"] = "test override"

    rec_path = tmp_path / "rec.yaml"
    ann_path = tmp_path / "ann.yaml"
    rec_path.write_text(yaml.dump(rec))
    ann_path.write_text(yaml.dump(ann))

    out = generate(recommendations_path=rec_path, annotations_path=ann_path)
    overridden = next(d for d in out["decisions"] if d["key"] == target["key"])
    assert overridden["decision"] == "EXCLUDED-REDUNDANT"
    assert overridden["contribution_class"] == "redundant"


def test_unratified_recommendation_raises(tmp_path: Path) -> None:
    """A recommendation with no governance ratification is fail-closed."""
    rec = yaml.safe_load(RECOMMENDATIONS_PATH.read_text())
    ann = yaml.safe_load(ANNOTATIONS_PATH.read_text())
    ann["annotations"] = ann["annotations"][:-1]  # drop one ratification

    rec_path = tmp_path / "rec.yaml"
    ann_path = tmp_path / "ann.yaml"
    rec_path.write_text(yaml.dump(rec))
    ann_path.write_text(yaml.dump(ann))

    with pytest.raises(ValueError, match="no governance ratification"):
        generate(recommendations_path=rec_path, annotations_path=ann_path)
