"""FPL scoring rules as typed, importable constants.

Each constant is annotated VERIFIED or UNVERIFIED:
- VERIFIED: confirmed against FPL bootstrap-static API for the stated season.
- UNVERIFIED: rule is known but has not been cross-checked against bootstrap-static;
  must not enter production scoring logic until confirmed.

Verification source: FPL bootstrap-static endpoint
  /api/bootstrap-static/ — fields: event_points, element_types[].cs_stop,
  element_types[].squad_min_play, game_settings.*

Last verified: season 2025/26

Defensive Contribution (2025/26 rule): DEF earn DC_POINTS for 10+ CBIT
(clearances + blocks + interceptions + tackles) actions in a match; MID/FWD
earn DC_POINTS for 12+ CBIRT (CBIT + recoveries) actions. The underlying
`tackles`, `recoveries`, `clearances_blocks_interceptions`,
`defensive_contribution` fields are staged through to the analytical mart as
plain per-fixture counts (additive across double-gameweek fixtures, like
`penalties_saved`). Applying `defensive_contribution_points()` to a
gameweek-summed `defensive_contribution` count is exact for single-fixture
gameweeks, but can disagree with FPL's true per-fixture-then-summed points for
the small population of double-gameweek rows where the per-fixture and summed
thresholds land on opposite sides of the boundary — see
research/foundation/composition/scoring_engine.ipynb section (d) for this caveat in a
total_points reconstruction.
"""

# ---------------------------------------------------------------------------
# Appearance
# ---------------------------------------------------------------------------

# VERIFIED 2025/26 — playing 1-59 min earns 1 point; 60+ earns 2 points.
APPEARANCE_MIN_MINUTES: int = 1
SHORT_APPEARANCE_POINTS: int = 1

FULL_APPEARANCE_MIN_MINUTES: int = 60
FULL_APPEARANCE_POINTS: int = 2

# The analytical population boundary IS the FPL full-appearance rule: pooling rows
# from below and above 60 minutes mixes observations generated by different scoring
# formulae. Single source of truth — consumers import this instead of re-hardcoding 60.
MINUTES_THRESHOLD: int = FULL_APPEARANCE_MIN_MINUTES  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Clean sheet
# ---------------------------------------------------------------------------

# The clean sheet eligibility threshold is the same rule as FULL_APPEARANCE_MIN_MINUTES.
# Both boundaries are generated by the same FPL game rule — pooling rows from below
# and above this threshold produces a target variable (total_points) that is not
# generated by the same scoring formula across all observations.
CLEAN_SHEET_MIN_MINUTES: int = FULL_APPEARANCE_MIN_MINUTES  # VERIFIED 2025/26

CLEAN_SHEET_POINTS_GK: int = 4  # VERIFIED 2025/26
CLEAN_SHEET_POINTS_DEF: int = 4  # VERIFIED 2025/26
CLEAN_SHEET_POINTS_MID: int = 1  # VERIFIED 2025/26
CLEAN_SHEET_POINTS_FWD: int = 0  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Goals conceded
# ---------------------------------------------------------------------------

# GK and DEF lose 1 point for every 2 goals conceded while on the pitch; MID/FWD exempt.
# The -1 coefficient and its GK/DEF-only applicability are VERIFIED 2026-07-08 against
# bootstrap-static game_config.scoring.goals_conceded ({GKP:-1, DEF:-1, MID:0, FWD:0}). The
# "per 2" divisor is NOT exposed by that endpoint and stays by-rule (see scoring diagnostics doc).
GOALS_CONCEDED_PER_PENALTY: int = 2  # UNVERIFIED (divisor not in bootstrap-static)
GOALS_CONCEDED_PENALTY_POINTS: int = -1  # VERIFIED 2026-07-08 (game_config.scoring.goals_conceded)

# ---------------------------------------------------------------------------
# Defensive Contribution (2025/26 rule)
# ---------------------------------------------------------------------------

# DC_POINTS (+2) and its position applicability (DEF/MID/FWD earn it, GK does not) are
# VERIFIED 2026-07-08 against bootstrap-static game_config.scoring.defensive_contribution
# ({DEF:2, MID:2, FWD:2, GKP:0}). The ACTION THRESHOLDS (10 CBIT / 12 CBIRT) are NOT exposed by
# that endpoint and stay by-rule (cross-checked empirically in scoring_engine.ipynb).
DC_CBIT_THRESHOLD_DEF: int = 10  # UNVERIFIED — CBIT (tackles+CBI) threshold for DEF (not in bootstrap-static)
DC_CBIRT_THRESHOLD_MID_FWD: int = 12  # UNVERIFIED — CBIRT (CBIT+recoveries) threshold for MID/FWD
DC_POINTS: int = 2  # VERIFIED 2026-07-08 (game_config.scoring.defensive_contribution)


def defensive_contribution_points(position: str, defensive_contribution: int) -> int:
    """2pts if `defensive_contribution` meets the position's CBIT/CBIRT threshold.

    DEF use the CBIT threshold; MID/FWD use the CBIRT threshold; GK are not
    subject to this rule. Applying this to a gameweek-summed
    `defensive_contribution` count is exact for single-fixture gameweeks, but
    can disagree with FPL's true per-fixture-then-summed points for the small
    population of double-gameweek rows — see scoring_engine.ipynb section (d).
    """
    if position == "DEF":
        return DC_POINTS if defensive_contribution >= DC_CBIT_THRESHOLD_DEF else 0
    if position in ("MID", "FWD"):
        return DC_POINTS if defensive_contribution >= DC_CBIRT_THRESHOLD_MID_FWD else 0
    return 0


# ---------------------------------------------------------------------------
# Goals
# ---------------------------------------------------------------------------

GOAL_POINTS_GK: int = 10  # VERIFIED 2025/26 — corrected from 6 (API game_config: 10 for GKP)
GOAL_POINTS_DEF: int = 6  # VERIFIED 2025/26
GOAL_POINTS_MID: int = 5  # VERIFIED 2025/26
GOAL_POINTS_FWD: int = 4  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Assists and penalties
# ---------------------------------------------------------------------------

ASSIST_POINTS: int = 3  # VERIFIED 2025/26
PENALTY_MISS_POINTS: int = -2  # VERIFIED 2025/26
OWN_GOAL_POINTS: int = -2  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Discipline
# ---------------------------------------------------------------------------

YELLOW_CARD_POINTS: int = -1  # VERIFIED 2025/26

RED_CARD_POINTS: int = -3  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Goalkeeping
# ---------------------------------------------------------------------------

GK_SAVES_PER_POINT: int = 3  # VERIFIED 2025/26 — 1 point per 3 saves
GK_PENALTY_SAVE_POINTS: int = 5  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Bonus Point System (BPS)
# ---------------------------------------------------------------------------

# Top 3 BPS performers each gameweek receive bonus points.
BPS_BONUS_FIRST: int = 3  # VERIFIED 2025/26
BPS_BONUS_SECOND: int = 2  # VERIFIED 2025/26
BPS_BONUS_THIRD: int = 1  # VERIFIED 2025/26


# ---------------------------------------------------------------------------
# Total-points reconstruction
# ---------------------------------------------------------------------------


def decompose_total_points(
    position: str,
    minutes: int,
    goals_scored: int,
    assists: int,
    clean_sheets: int,
    goals_conceded: int,
    saves: int,
    penalties_saved: int,
    bonus: int,
    yellow_cards: int,
    red_cards: int,
    own_goals: int,
    penalties_missed: int,
    defensive_contribution: int,
) -> dict[str, int]:
    """Per-component point contributions for one player-gameweek (pure formula).

    Scalars in, ``{component: points}`` out; the values sum to the FPL
    ``total_points`` for single-fixture gameweeks. Exact for SGW rows; for the
    small population of double-gameweek rows the ``defensive_contribution``
    component can disagree with FPL's per-fixture-then-summed points (see
    ``defensive_contribution_points`` and composition/scoring_engine.ipynb
    section (d)). No pandas — vectorise by mapping over rows.
    """
    goal_points = {
        "GK": GOAL_POINTS_GK,
        "DEF": GOAL_POINTS_DEF,
        "MID": GOAL_POINTS_MID,
        "FWD": GOAL_POINTS_FWD,
    }
    clean_sheet_points = {
        "GK": CLEAN_SHEET_POINTS_GK,
        "DEF": CLEAN_SHEET_POINTS_DEF,
        "MID": CLEAN_SHEET_POINTS_MID,
        "FWD": CLEAN_SHEET_POINTS_FWD,
    }
    appearance = FULL_APPEARANCE_POINTS if minutes >= FULL_APPEARANCE_MIN_MINUTES else SHORT_APPEARANCE_POINTS
    conceded = (
        (goals_conceded // GOALS_CONCEDED_PER_PENALTY) * GOALS_CONCEDED_PENALTY_POINTS
        if position in ("GK", "DEF")
        else 0
    )
    return {
        "appearance": appearance,
        "goals": goals_scored * goal_points[position],
        "assists": assists * ASSIST_POINTS,
        "clean_sheets": clean_sheets * clean_sheet_points[position],
        "saves": (saves // GK_SAVES_PER_POINT) if position == "GK" else 0,
        "penalties_saved": penalties_saved * GK_PENALTY_SAVE_POINTS,
        "bonus": bonus,
        "defensive_contribution": defensive_contribution_points(position, defensive_contribution),
        "goals_conceded": conceded,
        "cards": yellow_cards * YELLOW_CARD_POINTS + red_cards * RED_CARD_POINTS,
        "own_goals": own_goals * OWN_GOAL_POINTS,
        "penalties_missed": penalties_missed * PENALTY_MISS_POINTS,
    }
