"""FPL scoring rules as typed, importable constants.

Each constant is annotated VERIFIED or UNVERIFIED:
- VERIFIED: confirmed against FPL bootstrap-static API for the stated season.
- UNVERIFIED: rule is known but has not been cross-checked against bootstrap-static;
  must not enter production scoring logic until confirmed.

Verification source: FPL bootstrap-static endpoint
  /api/bootstrap-static/ — fields: event_points, element_types[].cs_stop,
  element_types[].squad_min_play, game_settings.*

Last verified: season 2025/26
"""

# ---------------------------------------------------------------------------
# Appearance
# ---------------------------------------------------------------------------

# VERIFIED 2025/26 — playing 1-59 min earns 1 point; 60+ earns 2 points.
APPEARANCE_MIN_MINUTES: int = 1
SHORT_APPEARANCE_POINTS: int = 1

FULL_APPEARANCE_MIN_MINUTES: int = 60
FULL_APPEARANCE_POINTS: int = 2

# ---------------------------------------------------------------------------
# Clean sheet
# ---------------------------------------------------------------------------

# The clean sheet eligibility threshold is the same rule as FULL_APPEARANCE_MIN_MINUTES.
# Both boundaries are generated by the same FPL game rule — pooling rows from below
# and above this threshold produces a target variable (total_points) that is not
# generated by the same scoring formula across all observations.
CLEAN_SHEET_MIN_MINUTES: int = FULL_APPEARANCE_MIN_MINUTES  # VERIFIED 2025/26

CLEAN_SHEET_POINTS_GK: int = 4    # VERIFIED 2025/26
CLEAN_SHEET_POINTS_DEF: int = 4   # VERIFIED 2025/26
CLEAN_SHEET_POINTS_MID: int = 1   # VERIFIED 2025/26
CLEAN_SHEET_POINTS_FWD: int = 0   # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Goals
# ---------------------------------------------------------------------------

GOAL_POINTS_GK: int = 10  # VERIFIED 2025/26 — corrected from 6 (API game_config: 10 for GKP)
GOAL_POINTS_DEF: int = 6  # VERIFIED 2025/26
GOAL_POINTS_MID: int = 5  # VERIFIED 2025/26
GOAL_POINTS_FWD: int = 4  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Assists and penalties
# ---------------------------------------------------------------------------

ASSIST_POINTS: int = 3         # VERIFIED 2025/26
PENALTY_MISS_POINTS: int = -2  # VERIFIED 2025/26
OWN_GOAL_POINTS: int = -2      # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Discipline
# ---------------------------------------------------------------------------

YELLOW_CARD_POINTS: int = -1  # VERIFIED 2025/26

RED_CARD_POINTS: int = -3  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Goalkeeping
# ---------------------------------------------------------------------------

GK_SAVES_PER_POINT: int = 3     # VERIFIED 2025/26 — 1 point per 3 saves
GK_PENALTY_SAVE_POINTS: int = 5  # VERIFIED 2025/26

# ---------------------------------------------------------------------------
# Bonus Point System (BPS)
# ---------------------------------------------------------------------------

# Top 3 BPS performers each gameweek receive bonus points.
BPS_BONUS_FIRST: int = 3   # VERIFIED 2025/26
BPS_BONUS_SECOND: int = 2  # VERIFIED 2025/26
BPS_BONUS_THIRD: int = 1   # VERIFIED 2025/26
