"""Schema + loaders for per-lens evaluation verdict records (ADR-009 Phase C).

The lens validate stage is the lens decision-of-record (adlc §2). Each lens emits
its verdict as two committed artifacts under ``research/families/<fam>/validate/``:

  ``evidence.yaml``      machine-written, (re)generated by ``study.run()``, never
                         hand-edited. Per studied (signal, position): the computed
                         statistics — ``rho_pooled``, ``rho_ci_lower/upper``,
                         ``block_stability_count``, ``decision_class`` — plus an
                         ``evidence_run`` pointer to the run that produced them.

  ``annotations.yaml``   human-authored judgment. Per (signal, position):
                         ``lifecycle_state``, ``downstream_status``, ``leakage_risk``,
                         ``behavioral_reason``, ``source_gate_decisions``, optional
                         ``notes``, and — for ontologically ``not_applicable``
                         positions (no evidence row) or judgment overrides — a
                         ``decision_class``.

``model/governance/generate_evaluation_metadata.py`` reads these file-based (no
import of ``research``) and merges them with ``synth01_decisions.yaml`` to (re)produce
``evaluation_metadata.yaml``. This module owns only the shapes + loaders; it performs
no merge and makes no decision.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

# Lens label (as it appears in evaluation_metadata.yaml / finding keys) -> the
# research family validate directory that owns its verdict records.
LENS_VALIDATE_DIRS: dict[str, Path] = {
    "FORM": Path("research/families/form/validate"),
    "AVAIL": Path("research/families/availability/validate"),
    "MARKET": Path("research/families/market/validate"),
    "FIXTURE-GW": Path("research/families/fixture/validate"),
}

# Study population label -> the governance/runtime position label.
POSITION_LABEL = {"GKP": "GK", "GK": "GK", "DEF": "DEF", "MID": "MID", "FWD": "FWD"}

EVIDENCE_FIELDS = ("rho_pooled", "rho_ci_lower", "rho_ci_upper", "block_stability_count", "decision_class")


@dataclass(frozen=True)
class LensVerdict:
    """One lens's loaded verdict records: evidence + annotations, by signal/position."""

    lens: str
    target: str
    evidence_run: dict[str, Any]
    # signal -> position -> {evidence field: value}
    evidence: dict[str, dict[str, dict[str, Any]]]
    # signal -> position -> {annotation field: value}
    annotations: dict[str, dict[str, dict[str, Any]]]


def _read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Verdict record not found at {path}. Run from the project root directory.")
    with path.open() as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"Verdict record at {path} must be a YAML mapping, got {type(data).__name__}")
    return data


def load_lens_verdict(lens: str, validate_dir: Path | None = None) -> LensVerdict:
    """Load the evidence + annotations records for one lens."""
    base = validate_dir if validate_dir is not None else LENS_VALIDATE_DIRS[lens]
    ev = _read_yaml(base / "evidence.yaml")
    ann = _read_yaml(base / "annotations.yaml")
    if ev["lens"] != lens or ann["lens"] != lens:
        raise ValueError(
            f"Lens mismatch in {base}: expected {lens!r}, got evidence={ev['lens']!r} annotations={ann['lens']!r}"
        )
    if ev["target"] != ann["target"]:
        raise ValueError(f"Target mismatch in {base}: evidence={ev['target']!r} annotations={ann['target']!r}")
    return LensVerdict(
        lens=lens,
        target=ev["target"],
        evidence_run=ev.get("evidence_run", {}),
        evidence=ev.get("signals", {}),
        annotations=ann.get("signals", {}),
    )


def load_all_lens_verdicts(dirs: dict[str, Path] | None = None) -> list[LensVerdict]:
    """Load every lens verdict in a stable lens order."""
    mapping = dirs if dirs is not None else LENS_VALIDATE_DIRS
    return [load_lens_verdict(lens, base) for lens, base in mapping.items()]
